name: imprs-hd-lensing
channels:
  - conda-forge
  - nodefaults
dependencies:
  - camb
  - fitsio
  - healpix
  - healpy
  - ipywidgets
  - matplotlib-base
  - notebook
  - numba
  - numpy
  - rich==13.7.*
  - scipy
  - treecorr
  - pip
  - pip:
    - glass
    - glass.ext.camb
    - heracles
