name: imprs-hd-lensing
channels:
  - conda-forge
  - nodefaults
dependencies:
  - camb
  - fitsio
  - healpix
  - healpy
  - ipywidgets
  - matplotlib-base
  - notebook
  - numba
  - numpy
  - python==3.12.*
  - rich
  - scipy
  - treecorr
  - pip
  - pip:
    - git+https://github.com/glass-dev/glass.git
    - glass.ext.camb
    - heracles
